### ISSUE TITLE
ctrl+C input 

### ISSUE THREAD

**Issue by Phenix54s** [me2d13/luamacros#10]
Hi
lmc_send_keys("^{V}")   this make ctrl+V like it correctly BUT 

lmc_send_keys("^{C}")  make something strange ... after using  keyboard testers , it seems  this make  << ctrl + shift + C >> input  ( tested with multiple keyboards )

EDIT : in fact every time i want ctrl key in a macro it  use ctrl+shift 

any ideas to fix  it ?

**Comment by me2d13** [comment]
Noted, tested, strange.
Would need to debug to see what's wrong.
But keyboard shortcuts are low prio for me.
Also I plan to rewrite this send key function (there's another bug related to UTF-8)

**Comment by 3ZadeSSG** [comment]
try using 
 lmc_send_keys("^(c)") for simulation of Ctrl+C
 lmc_send_keys("^(v)") for Ctrl+V

just replacing { } with ( ), helped in my case, and it does not sends CTRL+Shift+C or CTRL+Shift+V, i have used it on my own to map my secondary keyboard for basic keyboard combination functions.

**Comment by hcgernhardtiii** [comment]
Sendkeys() is case sensitive.  Thus, "^C"  sends ctrl+shift+C, whereas "^c" sends ctrl+C.

**Comment by me2d13** [comment]
Also [this way](http://www.hidmacros.eu/forum/viewtopic.php?f=12&t=475)  should work better
