### ISSUE TITLE
Feature Request : Delay/Sleeps between keystrokes

### ISSUE THREAD

**Issue by enthusiasticlulu** [me2d13/luamacros#12]
Hi Petr,
This is a request for optional delay/sleeps between keystrokes, as suggested here : http://www.hidmacros.eu/forum/viewtopic.php?f=6&t=308
Thanks a lot!
Lulu

**Comment by me2d13** [comment]
Implemented, see http://www.hidmacros.eu/forum/viewtopic.php?f=6&t=308&p=1360#p1360
