### ISSUE TITLE
Feature Request: make macro triggers recognize virtual key codes

### ISSUE THREAD

**Issue by enthusiasticlulu** [me2d13/luamacros#13]
Hi Petr,
As suggested here: http://www.hidmacros.eu/forum/viewtopic.php?f=6&t=432
This is a request to make macro triggers recognize virtual key codes instead of their representation by keyboard's regional settings.
Thank you so much!

**Comment by me2d13** [comment]
See http://www.hidmacros.eu/forum/viewtopic.php?f=6&t=432&p=1361#p1361 - this should cover requested feature.
