### ISSUE TITLE
Only affects single user (normal or admin), will not run 2 instances at once

### ISSUE THREAD

**Issue by RobRimmer** [me2d13/luamacros#14]
After having a problem with an app running in administrator mode not getting mapped keys, I found that luamacros seems to affect only the user that ran the script.
ie If I run as me, it does not affect apps running in admin mode, if I run in admin mode, it does not affect apps that I run in normal mode.
Attempting to start 2 instances of luamacros (one normal, one admin) causes the 2nd instance to crash on startup (regardless of the order)

**Comment by me2d13** [comment]
The second instance should not crash (and if it does I'll fix it) but LuaMacros can't run with 2 instances and I do not plan to change it. It's because of its architecture and implement multi-user feature would require big changes.
