### ISSUE TITLE
Cannot compile - error in TKeyLogService

### ISSUE THREAD

**Issue by ronh991** [me2d13/luamacros#15]
Trying to compile your luamacros.  First was the issue with ExtraHighliters, which was fixed by downloading the update by the person from dec issue.

Now I get the following, but the function is there.  I have made no other changes.

error:

ukeylogservice.pas(56,25) Error: function header doesn't match any method of this class "AddRaw(PRAWINPUT):^TKeyStroke;"

What version of lazarus are you using?

code:

TKeyLogService = class
    private
      fLog: Array[0..cLogArrayLength] of TKeyLogItem;
      fIndex: Integer; // points to first free block
      fJustScannedKs: TKeyStroke;
      procedure AssignDeviceInLogRange(var pKS: TKeyStroke; pSearchCount: Integer);
      function KeyStrokeEqual(p1, p2: TKeyStroke): boolean;
    public
      constructor Create;
      function AddRaw(pRawdata: PRAWINPUT): TKeyStrokePtr;
      procedure AssignDevice(var pKS: TKeyStroke);
      procedure RemoveOldItems;
      procedure ResetScanned;
      property JustScannedKs: TKeyStroke read fJustScannedKs;
  end;

later

function TKeyLogService.AddRaw(pRawdata: PRAWINPUT): TKeyStrokePtr;
begin
  case pRawdata^.keyboard.Message of
    WM_KEYDOWN, WM_SYSKEYDOWN: fLog[fIndex].KeyStroke.Direction:=cDirectionDown;
    WM_KEYUP, WM_SYSKEYUP: fLog[fIndex].KeyStroke.Direction:=cDirectionUp;
  end;
  fLog[fIndex].TimeStamp:=Glb.UnixTimestampMs;
  fLog[fIndex].KeyStroke.DeviceHandle:=pRawdata^.header.hDevice;
  fLog[fIndex].KeyStroke.VKeyCode:=pRawdata^.keyboard.VKey;
  Result := @(fLog[fIndex].KeyStroke);
  if (Glb.ScanService.Scanning) and (fLog[fIndex].KeyStroke.Direction=cDirectionDown) then
  begin
    fJustScannedKs := fLog[fIndex].KeyStroke;
    Glb.DebugLog('Recorder scanned keystroke', cLoggerHook);
  end;
  fIndex:=(fIndex+1) mod cLogArrayLength;
end;

**Comment by me2d13** [comment]
I'm using Lazarus 1.2.6. I'm able to compile this unit at 2 different computers with no issues. Also as you can see the method declaration is the same in class and implementation.
Seems to be some local problem, not a code issue.

**Comment by ronh991** [comment]
Okay thanks,

I am using 1.8 RC2 - I see that the mrandreastoth has a fork updated to work with a later versions.  I am also working on a Simconnect.pas file for P3D v4 (uses simconnect SP2 Acceleration). I have tested this on your hidmacros and got simconnect to connect to hidmacros, but I have other issues with lazarus and hidmacros.  So I am trying luamacros.  Thanks for a great program.
