### ISSUE TITLE
Virtual-key code

### ISSUE THREAD

**Issue by quirinux** [me2d13/luamacros#21]
It would be great if there was an option to send a virtual key code like described [on msdn here](https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx)

It would open the possibilities to infinite possibilities once lua macros is used beyond flight simulator programs, a good use for that are:

- send media keys
- send non European char
- send special keys, like browser or windows key
- much more

**Comment by me2d13** [comment]
Already there, see http://www.hidmacros.eu/forum/viewtopic.php?f=12&t=475

**Comment by quirinux** [comment]
Ya sorry about that stupid question, I found it latter, but there are some very important documentation missing for luamacros, I will try to provide some good descriptions for each available function soon, publish on my own github repository and let you guys decide to include on the main project's wiki page, I believe it worth it, indeed to myself int the future

cheers

**Comment by me2d13** [comment]
Yes, that was my plan to update wiki with all possible commands, but I'm too tired with coding to write docs :-).
So if you can help with that, good, take this as reference of all possible commands: https://github.com/me2d13/luamacros/blob/master/src/uluaengine.pas#L975

**Comment by quirinux** [comment]
There it go my good Sir, first step is done, I will fill it bit by bit but I think the main ones are done this week yet

https://github.com/quirinux/luamacros-documentation/blob/master/README.md
