### ISSUE TITLE
lmc_send_keys('{NUMLOCK}') don't work

### ISSUE THREAD

**Issue by roxasremix** [me2d13/luamacros#23]
I'm trying to use lmc_send_keys('{NUMLOCK}') to switch between numpad to home, end, and the other keys but it doesn't work in any key ( i've tried with different numpad-only keyboards and other keyboard). Using lmc_send_keys('{CAPSLOCK}') and other special keys works fine, so I don't know what is the problem

**Comment by me2d13** [comment]
Use 
```
lmc_send_input(144, 0, 0)
lmc_send_input(144, 0, 2)
```
