### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by mileso** [me2d13/luamacros#24]
Trying to compile the latest version and uStatsForm is generating errors because TMemo.Lines.Add (TStrings.Add) only accepts one argument but there are multiple calls to Add with two arguments.  Example:

 Add('Refresh count of this window: %d', [fRefreshCount]);

I am using Lazarus 1.2.6 and I cannot find any documentation that TStrings.Add allows two parameters.  It looks like there is a missing Format() around the arguments.  Or is there something I am missing?

**Comment by me2d13** [comment]
I agree and I wonder how my compilation passed. There should be Format function around. I'll check once I'm at the computer with luamacros dev env.

**Comment by me2d13** [comment]
I'm using Lazarus 1.6 with free pascal 3.0 and it has such syntactic suger - see https://www.freepascal.org/docs-html/current/rtl/classes/tstrings.add.html
