### ISSUE TITLE
Not working in Steam in-home streaming

### ISSUE THREAD

**Issue by Blindmikey** [me2d13/luamacros#26]
Created a Lua macros script to reassign keys on a bluetooth numeric keypad to emulate wasd gaming keypad. Works locally, but when using it in Steam in-home streaming, the original numeric keys are sent instead of the remap.

I also tried running Luamacros as administrator, but no difference was found.

**Comment by me2d13** [comment]
Blocking original keys is in fact software hack and works only for applications that use standard windows messaging when reading keyboard. If the application is using different way (e.gg like luamacros itself) the keys are not blocked.
