### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by DarkAxi0m** [me2d13/luamacros#3]
Can you give me any hints on your build setup.
Mine is just throwing SIGSEGV errors whenever i run it.

Project LuaMacros raised exception class 'External: SIGSEGV'.
 At address 10002B71F

Builds ok, and other applications run fine.

Windows10, Lazarus 1.6, FPC 3.0.0

**Comment by me2d13** [comment]
Will do later sitting at my computer when returning back from vacation.
Just a hint: AFAIR there are LUA dlls needed for application to start. Make sure you have them at the same place as your exe. Probably the safest way is to download LuaMacros package, check it runs, build the exe file yourself, check it has similar size, then copy it to your downloaded location replacing downloaded exe.

**Comment by DarkAxi0m** [comment]
ahhh yes that is prob what i am missing.

**Comment by DarkAxi0m** [comment]
Bingo, had to copy the lua52-XXX.dll from lib into the out dir.

working now :)
