### ISSUE TITLE
New/Virtual Keys

### ISSUE THREAD

**Issue by sapioit** [me2d13/luamacros#30]
I see in the [Key Names](https://github.com/me2d13/luamacros/wiki/List-of-Keys) there is `F1`-`F24`, so I though of asking if there is any way to add our own custom virtual keys, like how the MouseButton4 and MouseButton5 are. 

I mean, I'd like to have a second keyboard with all the keys different from the main keyboard. Can I just have the second keyboard's keys `be`, `aa`, `ab`, `ac`, etc. and have them recognized by apps when setting hotkeys?

I want to play old same-screen multiplayer games using different keyboards (so they can both have assigned the exact same keys but on different keyboards).

**Comment by me2d13** [comment]
No.
Those keys are standard in windows - see https://docs.microsoft.com/en-us/windows/desktop/inputdev/virtual-key-codes. Just keyboards have usually only F1-10. But you can't add your own keys

**Comment by sapioit** [comment]
I understand.
Is it impossible to add new keys? I mean, not as a keyboard, but as having the keyboard be treated like a custom device (which apparently can have more/different keys).

**Comment by me2d13** [comment]
No. This is what custom keyboard driver could do, but luamacros is not such software
