### ISSUE TITLE
LuaMacros not working in different native Windows Applications

### ISSUE THREAD

**Issue by HoZe-Lukas** [me2d13/luamacros#32]
I registered that LuaMacros is working well in a lot of programms but in some default Windows programs it is absolutely not working correct. 
One example for this is the Microsoft Calculator. In here also if the key is set to a shortcut the calculator knows it is always getting the default keys first and the mapped shortcut.
For example if a value is in the calculator and you have the num1 key bound to ctr+c it will add the 1 to the number shown in the calculator and then copying the value to the clipboard but with the extra number.
This is always happening also when LuaMacros and the calculator is fresh started after a system boot.

**Comment by me2d13** [comment]
Yes, luamacros use kind of hack to block original key. There are apps that read keyboard "directly" and this hack doesn't work. There's nothing I can do with that.
