### ISSUE TITLE
Help - trying to get LuaMacros to read my HID device

### ISSUE THREAD

**Issue by AceHawk75** [me2d13/luamacros#34]
Hello. I have stumbled upon LuaMacros and I feel that this might be the solution for my current project. I am however unable to get it to "see" the HID device I am trying to work with.
I run the lmc_print_devices() and get some of the USB devices I have but not the one I need to work with.
Here is some of the definition items from the device I am trying to work with, perhaps there might be an easy reason why this device does not come up on the list (and hopefully a way to get it to do so!)

![clipboard01](https://user-images.githubusercontent.com/43395182/47400553-a6ed9400-d70b-11e8-86db-66d6444c9f7c.jpg)

**Comment by me2d13** [comment]
I do not plan to add support for special devices like this one. Quite edge case...
