### ISSUE TITLE
Send a Key combination on "release" , very new to this.

### ISSUE THREAD

**Issue by I3ordo** [me2d13/luamacros#35]
I would like to send  "+F13" to be sent ony when "button 86" is released.

 --  //if button 86 is released then send Shift+F13 

  if (button == 86) then         
    lmc_send_keys('+{F13}', 50)

//the structure of my currently working code is  like this.

lmc_device_set_name('OBSDeck','2FAD678D')
lmc_print_devices()
lmc.minimizeToTray = true
lmc_minimize()

lmc_set_handler('OBSDeck', function(button,direction)
  if (direction == 1) then return end

  if (button == 86) then         --V
    lmc_send_keys('+{F13}', 50)
  
elseif (button == 13) then   --enter
    lmc_send_keys('%<{ENTER}', 50)

  end
end
)

**Comment by I3ordo** [comment]
i guess luamacros or hidmacros dont support "up" "down" flags like AHK

**Comment by me2d13** [comment]
Your script looks ok. You haven't describe what doesn't work, what's the behavior. If lmc_send_keys doesn't work, use more flexible function lmc_send_input. Details are described at http://hidmacros.eu/forum/

**Comment by I3ordo** [comment]
"would like to send "+F13" to be sent """""""only"""""""" when "button 86" i
s """"released"""".
 Sorry for the initial typo.
The down vote is for closing the issue
Thanks

**Comment by I3ordo** [comment]
I think the solution if there is one; should be at this line.
"if (button == 86//button up flag here//) then

**Comment by me2d13** [comment]
You have the direction flag even in your code sample and ignores one direction. The flag is there and is supported. All handling is done in callback function, the initial if is useless (if this is your complete code). You still haven't described what's your current behavior - if you have double press, or no press...
I have nothing to add to my comment when closing this issue

**Comment by I3ordo** [comment]
current behaviour is when i press button "86" it sends the keys "+F13"

i dont want it to send "+F13" on press , just ONLY when i stop pressing "button 86"  thus lift my finger off.
i am not familiar with "double press" or "no press" concepts.

so is this the part where i dont understand?
"if (button == 86) then --V
lmc_send_keys('+{F13}', 50)"

and there is a direction part:
"if (direction == 1) then return end"

i dont understand what this part does.

My end code, i guess should seem something like this:

(button == 86) then --Maybe this should be (button == 86down)--
lmc_send_keys('+{F12}', 50)"

(button == 86) then --Maybe this should be (button == 86up)--
lmc_send_keys('+{F13}', 50)

**Comment by I3ordo** [comment]
found this:
lmc_set_handler('MACROS',function(button, direction)
	if (direction == 1) then return end -- ignore keydown

	if	(button == 67) then lmc_spawn("cmd") -- Keycode for C
	elseif	(button == string.byte('C') then lmc_spawn("cmd") -- Via String Byte
        else    print('Pressed button number ' .. button)
	end
end)

so basically my code already just works on key up/ ignoring key down

so that s why you could not understand my aim as my code was already doing the thign i want.  But my problem persists as i have to isolate that behaviour or it has to ignore "keydown" for some keys , not whole.

**Comment by me2d13** [comment]
direction contains 1 for key press and 0 for release. All you need to do is combine conditions (direction and button).
As stated - you can't use luamacros without scripting knowledge.

**Comment by I3ordo** [comment]
can you give me a two-line example where  button does work on press and other on release or let me try first, it wont work because i dont know how i add direction.

lmc_set_handler('OBSDeck', function(button,direction)
  if (direction == 1) then return end 

  if (button == 86) then     --how do i define press or release on "(button==86)"                                                  
    lmc_send_keys('+{F13}', 50) 
  if (button == 86) then                                                       
    lmc_send_keys('+{F14}', 50)
  end
end
)
