### ISSUE TITLE
Availability of a release

### ISSUE THREAD

**Issue by EveryOtherUsernameWasAlreadyTaken** [me2d13/luamacros#4]
Is there a ready-to-run release available for download for the non-programmers out there?

**Comment by me2d13** [comment]
Of course, read this: http://www.hidmacros.eu/forum/viewtopic.php?f=10&t=241

**Comment by EveryOtherUsernameWasAlreadyTaken** [comment]
When I come here (to the main site https://github.com/me2d13/luamacros), how am I supposed to know about this link? Yes, there is a link to the forum, but hey, that's a forum. I didn't expect a download link inside there. Perhaps you want to provide a download link directly on the main GitHub page.

In any case, thanks for the tool. I wrote a few really helpful macros which I can now access from a second keyboard. Nice work.

**Comment by me2d13** [comment]
Added
