### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by EveryOtherUsernameWasAlreadyTaken** [me2d13/luamacros#5]
I can write a LUA macro containing `lmc_send_keys('你好.')` and it saves and loads fine, displaying the Chinese characters. However, they don't get typed like that, e.g. in Notepad. Notepad will display the Chinese characters fine when I enter them directly. Is there a way to make it work in LuaMacros? Maybe it's a limitation of SendKeys()?

**Comment by me2d13** [comment]
Just checked, lmc_send_keys uses (at the end) windows api function keybd_event. This function probably cannot handle unicode characters and code should be rewritten to use SendInput (http://stackoverflow.com/questions/3726812/how-to-send-unicode-keys-with-c-keybd-event).

**Comment by mrsimb** [comment]
Up

**Comment by me2d13** [comment]
Implemented, see http://www.hidmacros.eu/forum/viewtopic.php?f=12&t=475#p1363
