### ISSUE TITLE
Second keyboard not disabled 

### ISSUE THREAD

**Issue by MarianJenis** [me2d13/luamacros#50]
Hi 
I recently created script and as I understand it, second keyboard should be disabled for normal input but it is not

**Comment by me2d13** [comment]
No, once you assign callback to device & key then standard function of the key should be blocked. For example if you have 2 keyboards and (via script) assign macro to key "A" on keyboard 1 then pressing A on keyboard 1 should execute the macro (script) and do not send letter A to active window. Pressing A on keyboard 2 should work as usual - just send A to active window.
In similar way you can assign macro (callback) to whole device (keyboard 1) then all keys on keyboard 1 should be blocked for standard processing, but keyboard 2 should work in usual way (as if luamacros is not running).
