### ISSUE TITLE
Errors compiling ExtraHighlighters_RT V1.0

### ISSUE THREAD

**Issue by dafzor** [me2d13/luamacros#9]
Trying to compile luamacros from source and getting the following errors on the ExtraHighlighters_RT library:

`Compile package ExtraHighlighters_RT 1.0: Exit code 1, Errors: 2, Hints: 2
syneditstrconstExtra.pas(4,6) Hint: Unit "SynEditStrConst" not used in SynEditStrConstExtra
synhighlighteradsp21xx.pas(210,47) Hint: Parameter "LineNumber" not used
synhighlighteradsp21xx.pas(1392,13) Error: Illegal type conversion: "TRangeState" to "Pointer"
synhighlighteradsp21xx.pas(1397,13) Error: Illegal type conversion: "Pointer" to "TRangeState"`

Tried to fix it using [PtrUInt](http://www.freepascal.org/docs-html/rtl/system/ptruint.html) function but just got more errors, not familiar with Object Pascal or Lazarus so probably doing something wrong.

**Comment by mrandreastoth** [comment]
The issues in ExtraHighklighters are only some of many errors in the third-party code that must be fixed before LuaMacros compiles and runs. I tried to locate a repository for ExtraHighlighters to see if the issues have been fixed, but I couldn't locate one, so proceeded to fix the various issue myself.

To fix the issues with ExtraHighlighters, locate the definition of TRangeState then add a new line that reads "PRangeState = ^RangeState;", The getters and setters then become...

function TSomething.GetRange: Pointer;
begin
  Result := Pointer(PRangeState(@fRange));
end;

procedure TSomething.SetRange(Value: Pointer);
begin
  fRange := PRangeState(Value)^;
end;

**Comment by mrandreastoth** [comment]
You can check out my ExtraHighlighters repository with the required fixes here: https://github.com/Andreas-Toth/ExtraHighlighters
